# Generated by Django 4.2 on 2023-06-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_envio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(),
        ),
    ]
